
services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - ./.env
    environment:
      MONGODB_URI: mongodb://db_mongodb:27017/gpi_database
    ports:
      - "3000:3000"
    depends_on:
      - db_mongodb
    networks: [appnet]

  frontend:
    build:
      context: ../proyecto-front-tite
      dockerfile: dockerfile
    depends_on:
      - backend
    ports:
      - "5170:80"
    networks: [appnet]

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks: [appnet]

  db_mongodb:
    image: mongo:7
    container_name: db_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - ./backups:/backups:ro
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    networks: [appnet]

networks:
  appnet:
    driver: bridge

volumes:
  mongodb-data:
